### ISSUE TITLE
Agregar Documentacion 

### ISSUE THREAD

**Issue by soranvb** [soranvb/ingweb#2]
agregarl a documentacion tenida hasta al momento

**Comment by GiiaG** [comment]
[documento.docx](https://github.com/soranvb/ingweb/files/1009647/documento.docx)
[dominio.docx](https://github.com/soranvb/ingweb/files/1009645/dominio.docx)
[FormatoCU.docx](https://github.com/soranvb/ingweb/files/1009646/FormatoCU.docx)

Voy a corregir unos detalles en los documentos, y falta el de diseño.

**Comment by GiiaG** [comment]
Yap.
